### PR TITLE
fix(sbb-button): remove submitter parameter

### LINKED ISSUE #1797: Bug: requestSubmit() is not working when sbb-button is of type="submit". (Throwing an error)
Bug: requestSubmit() is not working when sbb-button is of type="submit". (Throwing an error)

```html
<form>
  <sbb-button type="submit">Submit</sbb-button>
</form>
```
See also:
https://github.com/WICG/webcomponents/issues/814#issuecomment-1218452137

### PR DESCRIPTION
**Pull request by DavideMininni-Fincons**
## Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [pull request tracker](https://github.com/lyne-design-system/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes #1797 

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../REVIEW.md) for more information what is checked during review process.

## Changes

Changes in this pull request:

- the submitter parameter has been removed when calling `requestSubmit`;
- a new story has been added with the `sbb-button` in a `form` tag.

## Browsers

I tested the build on the following browsers:

- [ ] Firefox Desktop
- [x] Chrome Desktop
- [ ] Edge Desktop
- [ ] Safari Desktop
- [ ] Chrome Mobile
- [ ] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [ ] VoiceOver Safari Desktop
- [ ] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: src/global/helpers/eventing/action-element-handlers.ts [hunk 1]
```diff
@@ -68,7 +68,9 @@ function handleLinkButtonClick(event: MouseEvent): void {
     return;
   } else if (element.type === 'submit') {
     if (form.requestSubmit) {
-      form.requestSubmit(element);
+      // `form.requestSubmit(element);` seems not to work for CustomElements, so the `element` parameter has been removed;
+      // see also https://github.com/WICG/webcomponents/issues/814#issuecomment-1218452137
+      form.requestSubmit();
```
Comment (jeripeierSBB) [inline src/global/helpers/eventing/action-element-handlers.ts:73]:
```suggestion
      // `form.requestSubmit(element);` seems not to work for CustomElements, so the `element` parameter has been removed;
      // TODO: Check if solved in anyway, see also https://github.com/WICG/webcomponents/issues/814#issuecomment-1218452137
      form.requestSubmit();
```

**Review by jeripeierSBB — APPROVED** [review]
LGTM, please add a TODO so it's easier to find at a later time
