### PR TITLE
fix(sbb-popover): rename tooltip to popover and fix accessibility bugs

### LINKED ISSUE #2018: [Bug]: Tooltips are difficult to close with the keyboard
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Accessibility

### It affects the following packages

Components

### Which version of Lyne Components are you using

_No response_

### Operating system

_No response_

### Browser / Browser version

_No response_

### Input mode

None

### Additional settings

_No response_

### What happened?

The tooltips can only be closed via ESC. They are also not displayed when the element is focused with the keyboard.

Recommendation
The tooltips should be displayed when the element is focused with the keyboard or when the mouse pointer is moved over the element without requiring any additional interaction. 
They should be automatically hidden when the focus is no longer on the triggered element or when the mouse is moved.

### Steps to reproduce the issue

1. Step one
2. Step two
3. ...

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jeripeierSBB**
BREAKING CHANGE: Component `sbb-tooltip` has been renamed to `sbb-popover`.
Component `sbb-tooltip-trigger` has been renamed to `sbb-popover-trigger`
Attribute `sbb-tooltip-close` has been renamed to `sbb-popover-close`.
Every CSS tooltip variable has been renamed from `--sbb-tooltip-*` to `--sbb-popover-*` (including trigger).

Closes #2018

### CODE REVIEW

File: src/components/popover/popover/popover.ts [hunk 1]
```diff
@@ -379,55 +359,83 @@ export class SbbTooltipElement extends LitElement {
...
         Array.from(this.children).filter((e): e is HTMLElement => e instanceof window.HTMLElement),
       );
     if (firstFocusable) {
       setModalityOnNextFocus(firstFocusable);
       firstFocusable.focus();
+    } else {
+      this._overlay.setAttribute('tabindex', '0');
+      setModalityOnNextFocus(this._overlay);
+      this._overlay.focus();
+      this._overlay.removeEventListener('blur', this._blurListener);
```
Comment (kyubisation) [inline src/components/popover/popover/popover.ts:409]: Why is this necessary?

File: src/components/popover/popover/popover.ts [hunk 2]
```diff
@@ -379,55 +359,83 @@ export class SbbTooltipElement extends LitElement {
...
+      this._overlay.addEventListener('blur', this._blurListener, {
+        signal: this._popoverController.signal,
+      });
     }
   }
 
-  private _setTooltipPosition(): void {
+  private _blurListener = (): void => {
+    // When a blur occurs, we know that the popover has to be closed, because there are no interactive elements inside the popover.
+    // We have to ensure that window / tab change doesn't trigger closing. This can be achieved by checking visibilityState, which only works with setTimeout().
```
Comment (kyubisation) [inline src/components/popover/popover/popover.ts:418]: Nitpick; This line is longer than 100 characters and wraps around in the GitHub code comparison view. 😅

**Review by kyubisation — APPROVED** [review]
LGTM 👍

File: src/components/popover/popover/popover.ts (hunk 2 above)
Comment (jeripeierSBB) [reply src/components/popover/popover/popover.ts:418]: fixed :)

File: src/components/popover/popover/popover.ts (hunk 1 above)
Comment (jeripeierSBB) [reply src/components/popover/popover/popover.ts]: comment updated :) thanks

Comment (jeripeierSBB) [reply src/components/popover/popover/popover.ts]: comment updated :) thanks

File: src/components/core/a11y/focus.ts [hunk 3]
```diff
@@ -17,23 +17,23 @@ export const IS_FOCUSABLE_QUERY = [
...
 ): HTMLElement[] {
   const focusableEls = new Set<HTMLElement>();
 
-  function getFocusables(elements: HTMLElement[], filterFunc?: (el: HTMLElement) => boolean): void {
+  function getFocusables(elements: HTMLElement[], filter?: (el: HTMLElement) => boolean): void {
     for (const el of elements) {
-      if (filterFunc?.(el)) {
+      if (filter && !filter(el)) {
         continue;
       }
```
[the remark this answers is not in the document]
Comment (jeripeierSBB) [reply src/components/core/a11y/focus.ts:31]: Yes I intentionally inverted the logic because normally using a filter you define what you want to keep and not what you like to ignore. So now it should be lesse confusing to define a filter :-)

File: src/components/navigation/navigation-section/navigation-section.ts [hunk 4]
```diff
@@ -295,7 +295,7 @@ export class SbbNavigationSectionElement extends UpdateScheduler(LitElement) {
       this.closest('sbb-navigation')!.shadowRoot!.children,
     ) as HTMLElement[];
     const navigationFocusableElements = getFocusableElements(navigationChildren, {
-      filterFunc: (el) => el.nodeName === 'SBB-NAVIGATION-SECTION',
+      filter: (el) => el.nodeName === 'SBB-NAVIGATION-SECTION',
```
[the remark this answers is not in the document]
Comment (jeripeierSBB) [reply src/components/navigation/navigation-section/navigation-section.ts:298]: Absolutely! Thanks for this great catch!!

File: src/components/navigation/navigation/navigation.ts [hunk 5]
```diff
@@ -205,7 +205,7 @@ export class SbbNavigationElement extends UpdateScheduler(LitElement) {
   }
 
   private _trapFocusFilter = (el: HTMLElement): boolean => {
-    return el.nodeName === 'SBB-NAVIGATION-SECTION' && el.getAttribute('data-state') !== 'opened';
+    return el.nodeName !== 'SBB-NAVIGATION-SECTION' || el.getAttribute('data-state') === 'opened';
```
[the remark this answers is not in the document]
Comment (jeripeierSBB) [reply src/components/navigation/navigation/navigation.ts:208]: Yes

File: src/components/core/a11y/focus.ts
[the remark this answers is not in the document]
Comment (jeripeierSBB) [reply src/components/core/a11y/focus.ts:1]: I had the same thought, now we are two, so I spent the morning creating tests ;)

**Review by TomMenga — APPROVED** [review]
LGTM 👍
