### PR TITLE
fix(sbb-datepicker): add accessibility label and localize date

### LINKED ISSUE #1912: [Bug]: Date- and Timepicker - no indication of input correction
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Accessibility

### It affects the following packages

Components

### Which version of Lyne Components are you using

37.7

### Operating system

_No response_

### Browser / Browser version

_No response_

### Input mode

None

### Additional settings

_No response_

### What happened?

When an input value gets corrected, the change does not get communicated to a user who uses a screenreader.
This can be reproduced with JAWS and Voiceover iOS.

### Steps to reproduce the issue

1. Fill picker with wrong input
2. listen to change in JAWS

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by MarioCastigliano**
This PR Closes #1912  #1916

### CODE REVIEW

File: src/components/sbb-datepicker/sbb-datepicker.tsx [hunk 1]
```diff
@@ -270,7 +254,22 @@ export class SbbDatepicker implements ComponentInterface {
...
+
+    this._statusContainer.innerHTML = date
+      ? `${i18nDateChangedTo[this._currentLanguage]} ${ariaLiveFormatter.format(date)}`
+      : i18nNoDate[this._currentLanguage];
+  }
+
   public render(): JSX.Element {
-    return <Host></Host>;
+    return (
+      <p role="status" class="visually-hidden" ref={(ref) => (this._statusContainer = ref)}></p>
```
Comment (jeripeierSBB) [inline src/components/sbb-datepicker/sbb-datepicker.tsx:272]: If host is already hidden for screen reader, it should not be needed here?
```suggestion
      <p role="status" ref={(ref) => (this._statusContainer = ref)}></p>
```

File: src/components/sbb-datepicker/sbb-datepicker.scss [hunk 2]
```diff
@@ -1,3 +1,9 @@
+@use '../../global/styles' as sbb;
+
 :host {
-  display: none;
+  @include sbb.screen-reader-only;
+}
+
+.visually-hidden {
+  @include sbb.screen-reader-only;
 }
```
Comment (jeripeierSBB) [inline src/components/sbb-datepicker/sbb-datepicker.scss:9]: See other comment :)
```suggestion
```

File: src/components/sbb-datepicker/sbb-datepicker.tsx [hunk 3]
```diff
@@ -210,31 +191,34 @@ export class SbbDatepicker implements ComponentInterface {
...
           isDateAvailable(
-            newValueAsDate,
+            valueAsDate,
             this._element.dateFilter,
             this._inputElement?.min,
             this._inputElement?.max,
           ));
       toggleDatasetEntry(this._inputElement, 'sbbInvalid', !isValidOrEmpty);
-      this._emitChange();
+      this._emitChange(valueAsDate);
```
Comment (jeripeierSBB) [inline src/components/sbb-datepicker/sbb-datepicker.tsx:214]: Is this the only place we call _emitChange() ?

File: src/components/sbb-datepicker/sbb-datepicker.tsx [hunk 4]
```diff
@@ -270,7 +254,22 @@ export class SbbDatepicker implements ComponentInterface {
...
+    const ariaLiveFormatter = new Intl.DateTimeFormat(`${this._currentLanguage}-CH`, {
+      weekday: 'long',
+      year: 'numeric',
+      month: 'numeric',
+      day: 'numeric',
+    });
+
+    this._statusContainer.innerHTML = date
+      ? `${i18nDateChangedTo[this._currentLanguage]} ${ariaLiveFormatter.format(date)}`
+      : i18nNoDate[this._currentLanguage];
```
Comment (jeripeierSBB) [inline src/components/sbb-datepicker/sbb-datepicker.tsx:267]: Not sure how it would interfere with invalid state when you have form errors. would it then read "no date selected" and after something like "invalid date value" (or whatever)? So potentially it could be better to read only valid values (did it like so in time input)

File: src/components/sbb-datepicker/sbb-datepicker.tsx [hunk 5]
```diff
@@ -270,7 +254,22 @@ export class SbbDatepicker implements ComponentInterface {
...
 
+  private _setAriaLiveMessage(date: Date): void {
+    const ariaLiveFormatter = new Intl.DateTimeFormat(`${this._currentLanguage}-CH`, {
+      weekday: 'long',
+      year: 'numeric',
+      month: 'numeric',
+      day: 'numeric',
+    });
+
+    this._statusContainer.innerHTML = date
```
Comment (jeripeierSBB) [inline src/components/sbb-datepicker/sbb-datepicker.tsx:265]:
```suggestion
    this._statusContainer.innerText = date
```

File: src/components/sbb-datepicker/sbb-datepicker.e2e.ts [hunk 6]
```diff
@@ -189,7 +189,7 @@ describe('sbb-datepicker', () => {
       await page.setContent(template);
```
Comment (jeripeierSBB) [inline src/components/sbb-datepicker/sbb-datepicker.e2e.ts:189]: I'd appreciate if there is a test about aria-live messages (potentially you can copy something from my pull request)

**Review by jeripeierSBB — COMMENTED** [review]
Thanks a lot to address this various issues :)

File: src/components/sbb-datepicker/sbb-datepicker.tsx (hunk 3 above)
Comment (MarioCastigliano) [reply src/components/sbb-datepicker/sbb-datepicker.tsx:214]: Yes it is

**Review by jeripeierSBB — APPROVED** [review]
LGTM, thanks a lot :)
