### PR TITLE
fix(sbb-select): select shows selected value in form field instead of the label

### LINKED ISSUE #1827: [Bug]: Select shows selected value in form-field instead of the label
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

0.36.19

### Operating system

all

### Browser / Browser version

all

### Input mode

Mouse/Keyboard

### Additional settings

_No response_

### What happened?

If the value and the label of an sbb-option are not the same, the value is displayed instead of the label in the form field after selecting an option. Reproduceable with the following HTML markup.

### Steps to reproduce the issue

<sbb-form-field label="Train types">
  <sbb-select>
    <sbb-option value="Test-1" selected>Astoro</sbb-option>
    <sbb-option value="Test-2">Flirt</sbb-option>
    <sbb-option value="Test-3">Domino</sbb-option>
  </sbb-select>
</sbb-form-field>

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by DavideMininni-Fincons**
## Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [pull request tracker](https://github.com/lyne-design-system/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes #1827 

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../REVIEW.md) for more information what is checked during review process.

## Changes

Changes in this pull request:

- the `@Watch('selected')` on the sbb-option has been removed to avoid infinite loops;
- the  `selectionChange` event is triggered only in user interaction cases;
- the `@Watch('value')` on sbb-select now looks on values on the sbb-options to display the correct label;
- a new public `@Method` has been added to fetch the displayValue.

## Browsers

I tested the build on the following browsers:

- [ ] Firefox Desktop
- [ ] Chrome Desktop
- [ ] Edge Desktop
- [ ] Safari Desktop
- [ ] Chrome Mobile
- [ ] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [ ] VoiceOver Safari Desktop
- [ ] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: src/components/sbb-option/sbb-option.tsx [hunk 1]
```diff
@@ -149,6 +148,11 @@ export class SbbOption implements ComponentInterface {
   @Method()
   public async setSelectedViaUserInteraction(selected: boolean): Promise<void> {
     this.selected = selected;
+    this.selectionChange.emit({
```
Comment (kyubisation) [inline src/components/sbb-option/sbb-option.tsx:151]: Do we really need the payload from this event?
Because id, value and selected state could simply be read from the event `target`. Or am I misunderstanding the purpose?

**Review by kyubisation — APPROVED** [review]
Bascially LGTM 👍 
One question about event content.

File: src/components/sbb-option/sbb-option.tsx (hunk 1 above)
Comment (DavideMininni-Fincons) [reply src/components/sbb-option/sbb-option.tsx]: Great point, removed in [44c81bb](https://github.com/lyne-design-system/lyne-components/pull/1843/commits/44c81bb2443969c3ebc7ae3b341f2cde525a43f2) 👍

**Review by jeripeierSBB — APPROVED** [review]
Nice refactoring, thanks
