### PR TITLE
fix(sbb-datepicker): empty month bug, improve error validation, add blur event

### LINKED ISSUE #1859: [Bug]: Datepicker - Uncaught TypeError
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

37.7

### Operating system

_No response_

### Browser / Browser version

_No response_

### Input mode

Mouse/Keyboard

### Additional settings

_No response_

### What happened?

When removing the month of the input field (input: 15..2023) and pressing enter, the component throws an uncaught error.

It should return "undefined".

### Steps to reproduce the issue

1. remove the month from the input (15..2023)
2. look in the console

### Relevant log output

```shell
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'padStart')
    at SbbDatepicker._composeValueString (7124.082c94f0.iframe.bundle.js:1:9824)
    at SbbDatepicker._formatValue (7124.082c94f0.iframe.bundle.js:1:9495)
    at SbbDatepicker._formatAndUpdateValue (7124.082c94f0.iframe.bundle.js:1:10214)
    at SbbDatepicker._valueChanged (7124.082c94f0.iframe.bundle.js:1:10023)
    at _inputElement.addEventListener.signal (7124.082c94f0.iframe.bundle.js:1:7719)
```

### PR DESCRIPTION
**Pull request by MarioCastigliano**
## Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [pull request tracker](https://github.com/lyne-design-system/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes #1859 #1851 

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../REVIEW.md) for more information what is checked during review process.

## Changes

Changes in this pull request:

- Datepicker now fires a blur event when value is changed programmatically, to ensure compatibility with frameworks that rely on that event to validate state
- Datepicker now displays error state in case of incorrectly formatted dates (without using user-reserved class `.sbb-invalid`)
- It's possible to add `data-sbb-invalid` to an input inside a `sbb-form-field` to display error state for internal use 

## Browsers

I tested the build on the following browsers:

- [x] Firefox Desktop
- [x] Chrome Desktop
- [ ] Edge Desktop
- [x] Safari Desktop
- [ ] Chrome Mobile
- [ ] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [ ] VoiceOver Safari Desktop
- [ ] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: src/components/sbb-datepicker/sbb-datepicker.tsx [hunk 1]
```diff
@@ -203,10 +206,10 @@ export class SbbDatepicker implements ComponentInterface {
 
   private _formatValue(value: string): string {
     const match: RegExpMatchArray = value?.match(FORMAT_DATE);
-    if (!match || match.length <= 2) {
+    if (!match || match.length <= 2 || !match[2] || !match[3]) {
+      this._inputElement.dataset.sbbInvalid = 'true';
```
Comment (jeripeierSBB) [inline src/components/sbb-datepicker/sbb-datepicker.tsx:210]: For this logic I don't find tests, or do I miss something?

File: src/components/sbb-datepicker/sbb-datepicker.tsx [hunk 2]
```diff
@@ -236,7 +239,7 @@ export class SbbDatepicker implements ComponentInterface {
   /** Applies the correct format to values and triggers event dispatch. */
   private async _formatAndUpdateValue(value: string): Promise<void> {
     if (this._inputElement) {
-      this._inputElement.classList.remove('sbb-invalid');
+      delete this._inputElement.dataset.sbbInvalid;
```
Comment (jeripeierSBB) [inline src/components/sbb-datepicker/sbb-datepicker.tsx:242]: better use toggleDatasetEntry helper method

File: src/components/sbb-datepicker/sbb-datepicker.tsx [hunk 3]
```diff
@@ -247,7 +250,7 @@ export class SbbDatepicker implements ComponentInterface {
           this._inputElement?.max
         )
       ) {
-        this._inputElement.classList.add('sbb-invalid');
+        this._inputElement.dataset.sbbInvalid = 'true';
```
Comment (jeripeierSBB) [inline src/components/sbb-datepicker/sbb-datepicker.tsx:253]: better use toggleDatasetEntry helper method or else assign = ''. true is not needed.

File: src/components/sbb-form-field/sbb-form-field.tsx [hunk 4]
```diff
@@ -335,7 +335,8 @@ export class SbbFormField implements ComponentInterface {
     toggleDatasetEntry(
       this._element,
       'invalid',
-      this._input.classList.contains('sbb-invalid') ||
+      this._input.dataset.sbbInvalid === 'true' ||
```
Comment (jeripeierSBB) [inline src/components/sbb-form-field/sbb-form-field.tsx:338]:
```suggestion
      this._input.dataset.sbbInvalid ||
```

**Review by jeripeierSBB — CHANGES_REQUESTED** [review]
LGTM, some small changes wished. I'm just thinking wether we should change the logic in select and autocomplete as well? maybe in a separate PR?.

File: src/components/sbb-datepicker/sbb-datepicker.tsx (hunk 1 above)
Comment (MarioCastigliano) [reply src/components/sbb-datepicker/sbb-datepicker.tsx:210]: I'll implement one

**Review by jeripeierSBB — APPROVED** [review]
LGTM, please also wait for review of @kyubisation

**Review by kyubisation — CHANGES_REQUESTED** [review]
Nice work!
Some thoughts on marking invalid.

File: src/global/helpers/native-date-adapter.ts [hunk 5]
```diff
@@ -194,7 +194,7 @@ export class NativeDateAdapter implements DateAdapter<Date> {
   /** Returns the right format for the `valueAsDate` property. */
   public formatValueAsDate(value: string): Date {
     const values = value?.split('.');
-    if (!values || values.length <= 2 || values.some((v) => v === '')) {
+    if (!values || values.length <= 2 || values.some((v) => v === '' || v === '00')) {
```
Comment (kyubisation) [inline src/global/helpers/native-date-adapter.ts:197]: Why is this necessary? I don't yet understand why we check for '00' but not e.g. '0'.
This is not a problem, I would just like to understand it.

Comment (MarioCastigliano) [reply src/global/helpers/native-date-adapter.ts:197]: This method is called after the input value has been formatted (that's why we split using the "." and not other possible separators), hence any 0 is already padded to 00. If you try to input 12.0.2012, it will automatically change to 12.00.2012 and then be marked as wrong

Comment (MarioCastigliano) [reply src/global/helpers/native-date-adapter.ts:197]: I forgot to mention that we need to include this case as fault scenario because the Date constructor does allow 0s (and maybe also negative numbers), it just "overflows" like 12.00.2012 = 12.12.2011

Comment (kyubisation) [reply src/global/helpers/native-date-adapter.ts:197]: Ah, I see
However, `11.07.00` is technically a valid date (although it gets translated to `11.07.1900`).
Due to this, I think we should leave it as it is for now (even, if it is weird).
Or what do you think?

Comment (kyubisation) [reply src/global/helpers/native-date-adapter.ts:197]: Dscussed via Teams; Day and month should be validated against '00' and '0', but the year should be left as is.

**Review by jeripeierSBB — APPROVED** [review]
LGTM (again ;) )

**Review by kyubisation — APPROVED** [review]
LGTM 👍 
Thanks for the fixes!
