### PR TITLE
fix(sbb-radio-button-group): radio group state update

### LINKED ISSUE #2093: [Bug]: Selection Panel in wrong state
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

41.9

### Operating system

_No response_

### Browser / Browser version

Chrome

### Input mode

None

### Additional settings

_No response_

### What happened?

We add two selection panels with vanilla js in to the dom and make the first one selected. This works the first time but after selecting a date, we do the same process again. However, the first selction panel seems selected but has the sate "data-state=closing".

### Steps to reproduce the issue

1. Open https://dev-www.sbb.ch/de/abos-billette/abonnemente/halbtax-plus/detail.html -> selection panel "ÖV-Guthaben Jugend" is selected and its content expanded.
3. Select another date in the datepicker -> selection panel "ÖV-Guthaben Jugend" is selected but its content is not expanded. The data-state attribute is set to "closing"

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by dauriamarco**
Closes #2093

### CODE REVIEW

File: src/components/sbb-radio-button-group/sbb-radio-button-group.tsx [hunk 1]
```diff
@@ -185,11 +186,11 @@ export class SbbRadioButtonGroup implements ComponentInterface {
     this.didChange.emit({ value });
   }
 
-  private _updateRadios(): void {
-    const value = this.value ?? this._radioButtons.find((radio) => radio.checked)?.value;
+  private _updateRadios(initValue?: string): void {
+    this.value = initValue || this._radioButtons.find((radio) => radio.checked)?.value;
```
Comment (jeripeierSBB) [inline src/components/sbb-radio-button-group/sbb-radio-button-group.tsx:190]:
```suggestion
    this.value = initValue ?? this._radioButtons.find((radio) => radio.checked)?.value;
```

File: src/components/sbb-checkbox/sbb-checkbox.tsx [hunk 2]
```diff
@@ -115,6 +115,15 @@ export class SbbCheckbox implements ComponentInterface {
...
   public stateChange: EventEmitter<CheckboxStateChange>;
 
+  /**
+   * Internal event that emits when the input element is loaded.
+   */
+  @Event({
+    bubbles: true,
+    eventName: 'sbb-checkbox-loaded',
+  })
+  public sbbCheckboxLoaded: EventEmitter<void>;
```
Comment (jeripeierSBB) [inline src/components/sbb-checkbox/sbb-checkbox.tsx:125]: Somehow weird with the sbb prefix, but also somehow ok :D.
As it is triggered in connected callback, should it better be named sbbCheckboxConnected? @kyubisation your meaning?

**Review by jeripeierSBB — APPROVED** [review]
LGTM. thanks for the huge effort!
