### PR TITLE
fix(sbb-selection-panel): arrow navigation with radio-button-group should select the radio-button

### LINKED ISSUE #2188: [Bug]: Radio Button is not directly selected using arrow keys, when SbbRadioButton is wrapped in SbbSelectionPanel
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Accessibility

### It affects the following packages

Design Tokens

### Which version of Lyne Components are you using

0.42.6

### Operating system

MacOS

### Browser / Browser version

Chrome 119

### Input mode

Mouse/Keyboard

### Additional settings

_No response_

### What happened?

SbbRadioButtons are not directly selected with arrow keys, when SbbRadioButton are wrapped in SbbSelectionPanel without content or content forced open.

### Steps to reproduce the issue

1. open https://lyne-storybook.app.sbb.ch/?path=/story/components-sbb-selection-panel--with-radio-button-group-force-open
2. focus first radio button
3. use arrow keys (down key)
  - failure: arrow key navigation focus next radio button, but does not select them
  - expected: arrow key navigation focuses and selects next radio button

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by DavideMininni-Fincons**
## Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [pull request tracker](https://github.com/lyne-design-system/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes #2188 

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../REVIEW.md) for more information what is checked during review process.

## Changes

Changes in this pull request:

- using a `sbb-radio-button-group` within a `sbb-selection-panel`, when a radio-button is selected and an arrow key is pressed, the previous/next is focused and selected instead than only focused.

## Browsers

I tested the build on the following browsers:

- [ ] Firefox Desktop
- [x] Chrome Desktop
- [ ] Edge Desktop
- [ ] Safari Desktop
- [ ] Chrome Mobile
- [ ] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [ ] VoiceOver Safari Desktop
- [ ] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: src/components/radio-button/radio-button-group/radio-button-group.ts [hunk 1]
```diff
@@ -304,18 +304,9 @@ export class SbbRadioButtonGroup extends LitElement {
...
-    if (this._hasSelectionPanel) {
-      current = enabledRadios.findIndex((e: SbbRadioButton) => e === evt.target);
-      nextIndex = getNextElementIndex(evt, current, enabledRadios.length);
-    } else {
-      const checked: number = enabledRadios.findIndex((radio: SbbRadioButton) => radio.checked);
-      nextIndex = getNextElementIndex(evt, checked, enabledRadios.length);
-      enabledRadios[nextIndex].select();
-    }
-
+    const current = enabledRadios.findIndex((e: SbbRadioButton) => e === evt.target);
```
Comment (jeripeierSBB) [inline src/components/radio-button/radio-button-group/radio-button-group.ts:307]: In case it is a selection panel which has some content, it's not allowed to directly set selection for accessibility reasons. So what can be improved is, enhancing the check for this._hasSelectionPanel with a check for if the selection panel has also some content. As a result, direct selection would only happen, if a selection panel without a content is present.

File: src/components/radio-button/radio-button-group/radio-button-group.ts [hunk 2]
```diff
@@ -304,15 +304,14 @@ export class SbbRadioButtonGroup extends LitElement {
       return;
     }
 
-    let current: number;
```
Comment (jeripeierSBB) [inline src/components/radio-button/radio-button-group/radio-button-group.ts:307]: I think we have still an open issue: If you focus into the group, the currently selected option should be focused and not the first (but again, only in case of all panels do not have content). Afterwards I think we are close to the behavior of a radio button :)

**Review by jeripeierSBB — CHANGES_REQUESTED** [review]

File: src/components/radio-button/radio-button-group/radio-button-group.ts (hunk 2 above)
Comment (DavideMininni-Fincons) [reply src/components/radio-button/radio-button-group/radio-button-group.ts:307]: See commit 15edb6f

File: src/components/radio-button/radio-button-group/radio-button-group.ts [hunk 3]
```diff
@@ -241,7 +241,16 @@ export class SbbRadioButtonGroupElement extends LitElement {
...
+    if (this._hasSelectionPanel) {
+      const isParentPanelWithContent =
+        radio.parentElement.nodeName === 'SBB-SELECTION-PANEL' &&
+        isValidAttribute(radio.parentElement, 'data-has-content');
+
+      return (radio.checked || isParentPanelWithContent) && !radio.disabled && !this.disabled
+        ? 0
+        : -1;
+    }
+    return radio.checked && !radio.disabled && !this.disabled ? 0 : -1;
```
[the remark this answers is not in the document]
Comment (DavideMininni-Fincons) [reply src/components/radio-button/radio-button-group/radio-button-group.ts]: Done in acb2324

**Review by jeripeierSBB — APPROVED** [review]
LGTM, thanks

File: src/components/radio-button/radio-button-group/radio-button-group.ts [hunk 4]
```diff
@@ -262,17 +267,14 @@ export class SbbRadioButtonGroupElement extends LitElement {
...
-      nextIndex = getNextElementIndex(evt, current, enabledRadios.length);
-    } else {
-      const checked: number = enabledRadios.findIndex(
-        (radio: SbbRadioButtonElement) => radio.checked,
-      );
-      nextIndex = getNextElementIndex(evt, checked, enabledRadios.length);
+    const current: number = enabledRadios.findIndex((e: SbbRadioButtonElement) => e === evt.target);
+    const nextIndex: number = getNextElementIndex(evt, current, enabledRadios.length);
+
+    // Selection on arrow keypress is allowed only if all the selection-panel has no content.
```
Comment (dauriamarco) [inline src/components/radio-button/radio-button-group/radio-button-group.ts:273]:
```suggestion
    // Selection on arrow keypress is allowed only if all the selection-panels have no content.
```

File: src/components/radio-button/radio-button-group/radio-button-group.ts [hunk 5]
```diff
@@ -262,17 +267,14 @@ export class SbbRadioButtonGroupElement extends LitElement {
...
+    const allPanelHasNoContent: boolean = (
```
Comment (dauriamarco) [inline src/components/radio-button/radio-button-group/radio-button-group.ts:274]:
```suggestion
    const allPanelsHaveNoContent: boolean = (
```

**Review by dauriamarco — APPROVED** [review]
LGTM 👍  just a couple of comments about naming
