### PR TITLE
fix: set most recent input modality initial value

### LINKED ISSUE #1757: bug: the tooltip trigger shows the focus ring on tooltip close if no mouse event has happened on the page yet

### PR DESCRIPTION
**Pull request by dauriamarco**
Closes #1757.

### CODE REVIEW

File: src/global/helpers/eventing/input-modality-detector.ts [hunk 1]
```diff
@@ -76,7 +76,7 @@ class SbbInputModalityDetector {
   public get mostRecentModality(): SbbInputModality | null {
     return this._mostRecentModality;
   }
-  private _mostRecentModality: SbbInputModality | null = null;
+  private _mostRecentModality: SbbInputModality | null = 'mouse';
```
Comment (jeripeierSBB) [inline src/global/helpers/eventing/input-modality-detector.ts:79]: should we add a test case somehow and make a comment here why we use mouse as a default?

**Review by jeripeierSBB — APPROVED** [review]
LGTM
