### PR TITLE
fix(sbb-navigation): add accessibility recommendations and fix focus order

### LINKED ISSUE #1769: bug(sbb-navigation): accessibility and focusing order
Focusing order: if focus is in navigation section and you leave it, you should land on the trigger.
Only documentation: language selection should have aria-selected on it, and activated pages aria-current set to page.

### PR DESCRIPTION
**Pull request by dauriamarco**
Closes #1769.

### CODE REVIEW

**Review by jeripeierSBB — COMMENTED** [review]
Could also the home story be improved with aria-selected and aria-current ?

File: src/components/sbb-navigation-section/sbb-navigation-section.tsx [hunk 1]
```diff
@@ -163,6 +166,33 @@ export class SbbNavigationSection implements ComponentInterface {
...
+    this._element.addEventListener(
+      'keydown',
+      (event) => {
+        if (event.key !== 'Tab') {
+          return;
+        }
+
+        // Dynamically get first and last focusable element, as this might have changed since opening overlay
+        const elementChildren: HTMLElement[] = Array.from(
+          this._element.shadowRoot.querySelectorAll('*')
```
Comment (jeripeierSBB) [inline src/components/sbb-navigation-section/sbb-navigation-section.tsx:178]: Does IS_FOCUSABLE_QUERY not work here?

Comment (jeripeierSBB) [reply src/components/sbb-navigation-section/sbb-navigation-section.tsx:178]: Does this consider slotted elements?

Comment (jeripeierSBB) [reply src/components/sbb-navigation-section/sbb-navigation-section.tsx:178]: as isBreakpoint('zero', 'large') is called twice, I think we should use a common method

Comment (dauriamarco) [reply src/components/sbb-navigation-section/sbb-navigation-section.tsx:178]: The `getFocusableElements` method takes care of everything, checking the IS_FOCUSABLE_QUERY and taking in consideration slotted elements.

**Review by jeripeierSBB — CHANGES_REQUESTED** [review]
Accessibility feedback: When in navigation section and focusing back to navigation, focus should land not on the trigger, but the next element in the list. For shift+tab it has to land on the trigger as already implemented

File: src/components/sbb-navigation-section/sbb-navigation-section.tsx (hunk 1 above)
Comment (jeripeierSBB) [reply src/components/sbb-navigation-section/sbb-navigation-section.tsx:178]: @dauriamarco Can you create a card for that?

File: src/components/sbb-navigation-section/sbb-navigation-section.tsx [hunk 2]
```diff
@@ -181,13 +181,17 @@ export class SbbNavigationSection implements ComponentInterface {
         const firstFocusable = focusableElements[0] as HTMLElement;
         const lastFocusable = focusableElements[focusableElements.length - 1] as HTMLElement;
 
+        const actionToFocus = event.shiftKey
+          ? this._triggerElement
+          : (this._triggerElement.nextElementSibling as HTMLElement);
```
Comment (jeripeierSBB) [inline src/components/sbb-navigation-section/sbb-navigation-section.tsx:186]: I think it's a little bit risky to just us nextElementSibling as it can have some other elements, e.g. divider or whatever invisible span / element. What about searching for the next focusable element starting from trigger?

File: src/components/sbb-navigation-section/sbb-navigation-section.tsx [hunk 3]
```diff
@@ -163,6 +166,50 @@ export class SbbNavigationSection implements ComponentInterface {
...
+    this._element.addEventListener(
+      'keydown',
+      (event) => {
+        if (event.key !== 'Tab') {
+          return;
+        }
+
+        // Dynamically get first and last focusable element, as this might have changed since opening overlay
+        const navigationChildren: HTMLElement[] = Array.from(
+          this._element.parentElement.shadowRoot.querySelectorAll('*')
```
Comment (jeripeierSBB) [inline src/components/sbb-navigation-section/sbb-navigation-section.tsx:178]:
```suggestion
          this._triggerElement.closest('sbb-navigation').shadowRoot.querySelectorAll('*')
```

**Review by kyubisation — APPROVED** [review]
LGTM 👍

**Comment by kyubisation** [comment]
Also approved by Mürsel 👍

File: src/storybook/pages/home/home.common.tsx [hunk 4]
```diff
@@ -40,7 +43,7 @@ export const Navigation = (): JSX.Element => (
       <sbb-navigation-action id="nav-5">Deutsch</sbb-navigation-action>
       <sbb-navigation-action id="nav-6">Français</sbb-navigation-action>
       <sbb-navigation-action id="nav-7">Italiano</sbb-navigation-action>
-      <sbb-navigation-action id="nav-8" active>
+      <sbb-navigation-action aria-selected="true" id="nav-8" active>
```
Comment (jeripeierSBB) [inline src/storybook/pages/home/home.common.tsx:46]:
```suggestion
      <sbb-navigation-action aria-pressed="true" id="nav-8" active>
```

**Review by jeripeierSBB — CHANGES_REQUESTED** [review]

**Review by jeripeierSBB — APPROVED** [review]
Nice, thanks for addressing this issues!

**Review by jeripeierSBB — APPROVED** [review]
LGTM, thanks!
