### PR TITLE
fix(sbb-notification): fix notification animation

### LINKED ISSUE #2257: bug(sbb-notification): animation stucks
Since lit migration, it seems that sbb-notification fade in animation isn't looking smooth.

### PR DESCRIPTION
**Pull request by dauriamarco**
Closes #2257

### CODE REVIEW

File: src/components/notification/notification.ts [hunk 1]
```diff
@@ -202,7 +201,13 @@ export class SbbNotification extends LitElement {
         class="sbb-notification__wrapper"
         @transitionend=${(event: TransitionEvent) => this._onNotificationTransitionEnd(event)}
         @animationend=${(event: AnimationEvent) => this._onNotificationAnimationEnd(event)}
-        ${ref((el) => (this._notificationElement = el as HTMLElement))}
+        ${ref(async (el) => {
```
Comment (jeripeierSBB) [inline src/components/notification/notification.ts:204]: Would it be possible to not use ref at all? I'ts just we know that with SSR it can cause problems. So when we use it as little as possible we will not run into problems once.

File: src/components/notification/notification.stories.ts [hunk 2]
```diff
@@ -92,8 +92,7 @@ const pageContent = (): TemplateResult => html`
 
 const DefaultTemplate = (args: Args): TemplateResult => html`
   <sbb-notification
-    ${sbbSpread(args)}
-    disable-animation
```
[the remark this answers is not in the document]
Comment (dauriamarco) [reply src/components/notification/notification.stories.ts:96]: Nope, it wasn't adding the `disable-animation` attr and the notification would expand on page load.

File: src/components/notification/notification.ts [hunk 3]
```diff
@@ -118,6 +117,14 @@ export class SbbNotificationElement extends LitElement {
     SbbNotificationElement.events.didClose,
   );
 
+  private _open(): void {
+    if (this._state === 'closed') {
+      this._state = 'opening';
+      this._willOpen.emit();
+      this.disableAnimation && this._handleOpening();
```
Comment (jeripeierSBB) [inline src/components/notification/notification.ts:124]: is this still needed with 0.1ms animation duration?

**Review by jeripeierSBB — COMMENTED** [review]
Sadly Chromatic problem still open. something is weird with the notification since lit migration :D

File: src/components/notification/notification.ts (hunk 3 above)
Comment (dauriamarco) [reply src/components/notification/notification.ts:124]: I surely need it in closing, since I also use `this.disableAnimation` in the `_setNotificationHeight()` method to determine whether to calculate the height or not. So in this case I would keep them in for consistency.

File: src/components/notification/notification.scss [hunk 4]
```diff
@@ -40,6 +40,11 @@
   margin: 0;
   transition: margin var(--sbb-notification-animation-duration)
```
[the remark this answers is not in the document]
Comment (dauriamarco) [reply src/components/notification/notification.scss:41]: We need it to animate the margin at the close of the notification as well.

File: src/components/notification/notification.ts [hunk 5]
```diff
@@ -138,9 +145,13 @@ export class SbbNotificationElement extends LitElement {
     this._setInlineLinks();
   }
 
-  protected override firstUpdated(): void {
-    this._willOpen.emit();
+  protected override async firstUpdated(): Promise<void> {
+    this._notificationElement = this.shadowRoot.querySelector(
+      '.sbb-notification__wrapper',
+    ) as HTMLElement;
+    await this.updateComplete;
```
Comment (jeripeierSBB) [inline src/components/notification/notification.ts:152]: Could you maybe explain in a code comment why we have to wait here?

**Review by jeripeierSBB — APPROVED** [review]

**Review by jeripeierSBB — APPROVED** [review]
LGTM, thanks!
