### PR TITLE
fix(sbb-toggle): initial animation glitch

### LINKED ISSUE #2319: bug(toggle): toggle has initial animation glitch
When loading the sbb-toggle, first, the white part is visible all over the toggle width, then it's reduced to the desired width. Can be seen on https://lyne-storybook.app.sbb.ch/?path=/story/components-sbb-toggle-sbb-toggle--size-m during first load.

### PR DESCRIPTION
**Pull request by dauriamarco**
Closes #2319

### CODE REVIEW

File: src/components/toggle/toggle/toggle.ts [hunk 1]
```diff
@@ -67,6 +67,7 @@ export class SbbToggleElement extends LitElement {
   @property({ attribute: 'disable-animation', reflect: true, type: Boolean })
   public disableAnimation = false;
 
+  private _loaded = false;
```
Comment (jeripeierSBB) [inline src/components/toggle/toggle/toggle.ts:70]: would it work to just us hasUpdated of lit https://lit.dev/docs/components/lifecycle/?

**Review by jeripeierSBB — APPROVED** [review]
LGTM
