### PR TITLE
fix(sbb-datepicker): datepicker prev and next day buttons aria-label

### LINKED ISSUE #1898: bug(a11y): add more precise labels for next and previous day buttons
`sbb-datepicker-next-day` and `sbb-datepicker-previous-day` should have aria-labels like "Change to the next day, currently selected %s" to better indicate what happens.

specs:
 - "%" should be replaced by current date
 - If the field is today, the current date should instead be "Today"
 - If the field is empty, the prev/next buttons should be disabled

**translations next day:**
- de : "Zum nächsten Tag wechseln, derzeit ausgewählt %s"
- en:  "Change to the next day, currently selected %s"
- fr:  "Passer au jour suivant, actuellement sélectionné  %s"
- it:  "Passare al giorno successivo, attualmente selezionato %s"

**translations previous day:**
- en: "Change to the previous day, currently selected %s"
- de: "Zum vorherigen Tag wechseln, derzeit ausgewählt %s"
- it: "Passare al giorno precedente, attualmente selezionato %s"
- fr: "Passer au jour précédent, actuellement sélectionné %s"

**translations today:**
- en: "today"
- de: "heute"
- fr: "aujourd'hui"
- it: "oggi"

### PR DESCRIPTION
**Pull request by dauriamarco**
Closes #1898

### CODE REVIEW

File: src/components/sbb-datepicker-previous-day/sbb-datepicker-previous-day.tsx [hunk 1]
```diff
@@ -161,6 +177,25 @@ export class SbbDatepickerPreviousDay implements ComponentInterface, ButtonPrope
     return this._dateAdapter.today();
   }
 
+  private async _setAriaLabel(): Promise<void> {
```
Comment (jeripeierSBB) [inline src/components/sbb-datepicker-previous-day/sbb-datepicker-previous-day.tsx:180]: not sure if we should externalize this function to avoid code duplication between next and previous day buttons?

**Review by MarioCastigliano — APPROVED** [review]
Looking great, thanks for the work

**Review by jeripeierSBB — APPROVED** [review]
LGTM, thanks!
